import Head from "next/head";
import Link from "next/Link";
import styles from "../styles/Home.module.css";

import Button from "@mui/material/Button";

export default function Home() {
    return (
        <div className={styles.container}>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <div>
                <Link href="/retweeters/1529643878155841537">
                    <Button
                        variant="outlined"
                        sx={{ backgroundColor: "#fff", "&:hover": { backgroundColor: "#fff" } }}>
                        Retweeters
                    </Button>
                </Link>
            </div>
        </div>
    );
}
